{{- range $name, $config := .Values.mcpServers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  replicas: {{ $config.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      {{- if $config.serviceAccount }}
      serviceAccountName: {{ $config.serviceAccount.name | default "default" }}
      {{- end }}
      containers:
        - name: mcp-server
          image: "{{ $config.image.repository }}:{{ $config.image.tag | default "latest" }}"
          imagePullPolicy: {{ $config.image.pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: {{ $config.mcpServer.port }}
              protocol: TCP
          {{- if $config.mcpServer.args }}
          args: {{ toYaml $config.mcpServer.args | nindent 12 }}
          {{- end }}
          {{- with $config.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          # livenessProbe:
          #   httpGet:
          #     path: /mcp
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /mcp
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
{{- end }}