{{- range $name, $config := .Values.mcpServers }}
{{- if and $config.serviceAccount (hasKey $config.serviceAccount "create") (eq $config.serviceAccount.create true) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $config.serviceAccount.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $config.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
{{- end }}
{{- end }}
