{{- range .Values.mcpServers }}
{{- if and .serviceAccount.create (ne (.serviceAccount.name | default "") "default") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
{{- end }}
{{- end }}
