{{- range $name, $config := .Values.mcpServers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  type: ClusterIP
  ports:
    - port: {{ $config.mcpServer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $name }}
{{- end }}
