{{- if eq .Values.gradioUI.exposure.type "route" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.gradioUI.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.gradioUI.name }}
spec:
  {{- if .Values.gradioUI.exposure.host }}
  host: {{ .Values.gradioUI.exposure.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.gradioUI.name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: "edge"
    insecureEdgeTerminationPolicy: "Redirect"
{{- else if and (eq .Values.gradioUI.exposure.type "ingress") .Values.gradioUI.exposure.host }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.gradioUI.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{ .Values.gradioUI.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: "nginx"
  rules:
    - host: {{ .Values.gradioUI.exposure.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.gradioUI.name }}
                port:
                  number: 7860
{{- end }}
