---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gradioUI.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.gradioUI.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  type: "ClusterIP"
  ports:
    - port: 7860
      targetPort: 7860
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.gradioUI.name }}
