# Global configuration

global:
  namespace: intelligent-cd

inference:
  model: "my-model"
  url: "https://URL:PORT/v1"
  apiToken: ""
  tlsVerify: "true"

llamaStack:
  name: llama-stack
  # Optional: Override the default distribution name "rh-dev" with a custom image
  # image: "quay.io/opendatahub/llama-stack:odh"
  # image: "quay.io/opendatahub/llama-stack:rhoai-v2.23-latest"
  route:
    enabled: false

pipelines:
  enabled: true
  namespaceSuffix: "-pipelines"
  initJob:
    image: quay.io/alopezme/aws-cli:latest
  connection:
    secretName: dashboard-dspa-secret
    minioUsername: "minio"
    minioPassword: "minio123"
    minioEndpoint: "minio.minio.svc.cluster.local"
    minioPort: '9000'
    minioRegion: "none"
    scheme: "http"

RAG:
  enabled: true
  vector_db_id: "my_documents"


gradioUI:
  name: gradio
  replicaCount: 1

  image:
    repository: "quay.io/alopezme/intelligent-cd-gradio"
    tag: "latest"
    pullPolicy: Always

  exposure:
    # Type of exposure: none, ingress, or route
    type: "route"

  env:
    TOOLGROUPS_DENYLIST:
      - builtin::websearch
      - builtin::rag
      - mcp::github

    # ArgoCD configuration
    ARGOCD_BASE_URL: "https://argocd-server.openshift-gitops:443"
    ARGOCD_API_TOKEN: "<Token>"

    # GitHub MCP Server configuration
    # This is not deployed on OpenShift, but runs in GitHub.com
    GITHUB_MCP_SERVER_AUTH_TOKEN: ""
    # https://github.com/github/github-mcp-server/blob/main/docs/remote-server.md#remote-mcp-toolsets
    GITHUB_MCP_SERVER_TOOLSETS: "pull_requests, repos, issues"
    GITHUB_MCP_SERVER_READONLY: "true"

    # Security and logging
    LOG_LEVEL: "DEBUG" # DEBUG, INFO, WARNING, ERROR, CRITICAL

  # Resources
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "2Gi"

mcpServers:
  ocp-mcp-server:
    replicaCount: 1
    image:
      repository: "quay.io/alopezme/kubernetes-mcp-server"
      tag: "latest"
      pullPolicy: Always

    # MCP Server specific configuration
    mcpServer:
      port: 8080
      args:
        - "--sse-port"
        - "8080"
        - "--disable-destructive"
        - "--log-level"
        - "5"

    serviceAccount:
      create: true
      # Service account name (required if create=true, optional if create=false for existing SA)
      name: "ocp-mcp-server"

    rbac:
      clusterRole: "view" # cluster-admin / view / edit

  argocd-mcp-server:
    replicaCount: 1

    image:
      repository: "quay.io/alopezme/argocd-mcp"
      tag: "latest"
      pullPolicy: Always

    # MCP Server specific configuration
    mcpServer:
      # Port for the MCP server to listen on
      port: 3000
      # Add command to debug environment variables and start the server
      args:
        - "exec"
        - "argocd-mcp@latest"
        - "sse"
    serviceAccount:
      create: false
      # Service account name (required if create=true, optional if create=false for existing SA)
      name: default
      
  servicenow-mcp:
    image:
      repository: "quay.io/alopezme/servicenow-mcp"
      tag: "latest"
      pullPolicy: Always
    mcpServer:
      port: 8080
    env:
      SERVICENOW_INSTANCE_URL: "https://devInstance.service-now.com"
      SERVICENOW_USERNAME: "your-username"
      SERVICENOW_PASSWORD: "your-password"
      SERVICENOW_AUTH_TYPE: "basic"
      SERVICENOW_TOOL_PACKAGE: "service_desk"