# Global configuration

global:
  namespace: intelligent-cd

inference:
  model: "llama-3-2-3b"
  url: "https://URL:PORT/v1"
  apiToken: ""
  tlsVerify: "true"

llamaStack:
  name: llama-stack
  route:
    enabled: false

pipelines:
  enabled: true
  namespaceSuffix: "-pipelines"
  initJob:
    image: quay.io/alopezme/aws-cli:latest
  connection:
    secretName: dashboard-dspa-secret
    minioUsername: "minio"
    minioPassword: "minio123"
    minioEndpoint: "minio.minio.svc.cluster.local"
    minioPort: '9000'
    minioRegion: "none"
    scheme: "http"

RAG:
  enabled: true
  vector_db_id: "my_documents"


gradioUI:
  name: gradio
  replicaCount: 1

  image:
    repository: "quay.io/alopezme/intelligent-cd-gradio"
    tag: "latest"
    pullPolicy: Always

  exposure:
    # Type of exposure: none, ingress, or route
    type: "route"

  env:
    TOOLGROUPS_DENYLIST:
      - builtin::websearch
      - builtin::rag

    # ArgoCD configuration
    ARGOCD_BASE_URL: "https://argocd-server-openshift-gitops.apps.ocp.sandbox515.opentlc.com"
    ARGOCD_API_TOKEN: "<Token>"

    # Security and logging
    LOG_LEVEL: "DEBUG" # DEBUG, INFO, WARNING, ERROR, CRITICAL

  # Resources
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "2Gi"

mcpServers:
  - name: ocp-mcp-server
    replicaCount: 1
    image:
      repository: "quay.io/alopezme/kubernetes-mcp-server"
      tag: "latest"
      pullPolicy: Always

    # MCP Server specific configuration
    mcpServer:
      port: 8080
      args:
        - "--sse-port"
        - "8080"
        - "--disable-destructive"
        - "--log-level"
        - "5"

    serviceAccount:
      create: true
      # Service account name (required if create=true, optional if create=false for existing SA)
      name: "ocp-mcp-server"

    rbac:
      clusterRole: "view" # cluster-admin / view / edit

  - name: argocd-mcp-server
    replicaCount: 1

    image:
      repository: "quay.io/alopezme/argocd-mcp"
      tag: "latest"
      pullPolicy: Always

    # MCP Server specific configuration
    mcpServer:
      # Port for the MCP server to listen on
      port: 3000

    serviceAccount:
      create: false
      # Service account name (required if create=true, optional if create=false for existing SA)
      name: default
