---
kind: Secret
apiVersion: v1
metadata:
  name:  {{ .Values.llamaStack.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.llamaStack.name }}
stringData:
  INFERENCE_MODEL: {{ .Values.inference.model | quote }}
  VLLM_URL: {{ .Values.inference.url | quote }}
  VLLM_TLS_VERIFY: {{ .Values.inference.tlsVerify | quote }}
  VLLM_API_TOKEN: {{ .Values.inference.apiToken | quote }}
{{- if .Values.mcpServers }}
{{- if .Values.mcpServers.ocpMcpServer }}
  MCP_OCP_URL: "http://{{ .Values.mcpServers.ocpMcpServer.name }}:{{ .Values.mcpServers.ocpMcpServer.mcpServer.port }}"
{{- end }}
{{- if .Values.mcpServers.argocdMcpServer }}
  MCP_ARGOCD_URL: "http://{{ .Values.mcpServers.argocdMcpServer.name }}:{{ .Values.mcpServers.argocdMcpServer.mcpServer.port }}"
{{- end }}
{{- if .Values.mcpServers.servicenowMcp }}
  MCP_SERVICENOW_URL: "http://{{ .Values.mcpServers.servicenowMcp.name }}:{{ .Values.mcpServers.servicenowMcp.mcpServer.port }}"
{{- end }}
{{- if .Values.llamaStack.opentelemetry.enabled }}
  OTEL_SERVICE_NAME: {{ .Values.llamaStack.opentelemetry.otelServiceName }}
  TELEMETRY_SINKS: {{ .Values.llamaStack.opentelemetry.telemetrySinks }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.llamaStack.opentelemetry.otelExporterOtlpEndpoint }}
{{- end }}
{{- end }}
{{- if .Values.llamaStack.websearch.tavilyApiKey }}
  TAVILY_SEARCH_API_KEY: "{{ .Values.llamaStack.websearch.tavilyApiKey }}"
{{- end }}
type: Opaque
