---
kind: Secret
apiVersion: v1
metadata:
  name:  {{ .Values.llamaStack.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.llamaStack.name }}
stringData:
  INFERENCE_MODEL: {{ .Values.inference.model | quote }}
  VLLM_URL: {{ .Values.inference.url | quote }}
  VLLM_TLS_VERIFY: {{ .Values.inference.tlsVerify | quote }}
  VLLM_API_TOKEN: {{ .Values.inference.apiToken | quote }}
{{- range .Values.mcpServers }}
{{- if eq .name "ocp-mcp-server" }}
  MCP_OCP_URL: "http://{{ .name }}:{{ .mcpServer.port }}"
  MCP_OCP_TLS_VERIFY: "false"
{{- end }}
{{- if eq .name "argocd-mcp-server" }}
  MCP_ARGOCD_URL: "http://{{ .name }}:{{ .mcpServer.port }}"
  MCP_ARGOCD_TLS_VERIFY: "false"
{{- end }}
{{- end }}
type: Opaque
