---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.llamaStack.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.llamaStack.name }}
spec:
  ports:
    - name: http
      port: 8321
      targetPort: 8321
      protocol: TCP
  selector:
    app: {{ .Values.llamaStack.name }}
