{{- if .Values.s3Bucket.connection }}
---
kind: Secret
apiVersion: v1
metadata:
  name:  {{ .Values.s3Bucket.connection.secretName }}
  namespace: {{ .Values.global.namespace }}{{ .Values.pipelines.namespaceSuffix }}
  labels:
    app: {{ .Values.global.namespace }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3Bucket.connection.username }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3Bucket.connection.password }}
type: Opaque
{{- end }}